### ISSUE TITLE
Please upload to Maven Central =D

### ISSUE THREAD

**Issue by giflw** [gboersma/uml-java-doclet#2]
Hi
Do you have plans to upload to maven central? If so, the coordinates will stay the same?

Regards

**Comment by gboersma** [comment]
I will if I get a chance to do it. Not a high priority for me.

**Comment by bcopy** [comment]
@gboersma : we've open sourced our project, and not having uml-java-doclet on Maven Central is a showstopper for making plantUML diagrams more widely accessible - would you mind if we released a fork with the same GAV coordinates ? Would it be possible to release a v 1.0 version ?

**Comment by gboersma** [comment]
Brice:

Glad to hear you are finding it useful.

If you are willing to maintain the fork, please go for it. If you want to
take over maintaining uml-java-doclet, please be my guest. I have gotten
busy with my other work and this is not a high priority for me.

Cheers,
Gerald

**Comment by gboersma** [comment]
@bcopy I had some free time and fixed a number of bugs, but I don't really have time to post to Maven Central. Please feel free to publish as version 1.1. I added a tag to mark the latest in master as 1.1.

**Comment by bcopy** [comment]
How about using Jitpack ? It's super simple to deploy there and use !

Brice

**Comment by gboersma** [comment]
@bcopy That is an absolutely fantastic solution! Takes all the pain away. I have updated the README and tested getting release 1.1 this way. Good to see that JitPack also works for plugin dependencies. Thanks!

**Comment by olegshtch** [comment]
@chfourie have a fork published on Maven Central
